# Generated by Django 4.0.3 on 2022-04-07 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demandeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tribunal', models.CharField(max_length=60)),
                ('date_jugement', models.DateField(auto_now=True)),
                ('nom_president', models.CharField(max_length=60)),
                ('nom_demandeure', models.CharField(max_length=60)),
                ('nom', models.CharField(max_length=60)),
                ('local1', models.CharField(max_length=60)),
                ('nom_demande', models.CharField(max_length=60)),
                ('local2', models.CharField(max_length=60)),
                ('nom_notaire', models.CharField(max_length=60)),
                ('date_invitation', models.DateTimeField(auto_now=True)),
                ('num_inivation', models.CharField(max_length=60)),
                ('vehicul_type', models.CharField(max_length=60)),
                ('matricule', models.CharField(max_length=60)),
                ('date_accident', models.DateTimeField(auto_now=True)),
                ('lieu_accident', models.CharField(max_length=80)),
                ('nom_proces', models.CharField(max_length=60)),
                ('date_pv', models.DateTimeField(auto_now_add=True)),
                ('source_pv', models.CharField(max_length=60)),
                ('description_acc', models.TextField()),
                ('num_ordonance', models.CharField(max_length=60)),
                ('date_ordonance', models.DateField(auto_now_add=True)),
                ('type_vehicule', models.CharField(max_length=60)),
                ('date_expertise', models.DateField(auto_now=True)),
                ('dmg_materiel', models.CharField(max_length=100)),
                ('numero_dossier', models.CharField(max_length=60)),
                ('nom_avocat1', models.CharField(max_length=60)),
                ('nom_avocat2', models.CharField(max_length=60)),
                ('date_pledorie', models.DateField(auto_now_add=True)),
                ('nom_avocat', models.CharField(max_length=60)),
                ('nom_avocatdeux', models.CharField(max_length=60)),
                ('adminupload', models.FileField(upload_to='media')),
                ('cout_expertise', models.CharField(max_length=60)),
                ('honaire_avocat_demande', models.CharField(max_length=60)),
                ('cout_invitation', models.CharField(max_length=60)),
                ('avocat_honoraire_ordonnance_demandes', models.CharField(max_length=60)),
                ('avocat_honoraire_ordonnance_juge', models.CharField(max_length=60)),
                ('cout_information_expertise', models.CharField(max_length=60)),
                ('Demande_contradictoire', models.CharField(max_length=60)),
                ('période_assurance', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='postes',
            name='slug',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_femme',
            field=models.BooleanField(default=False, verbose_name='Is_femme'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_homme',
            field=models.BooleanField(default=False, verbose_name='Is_homme'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tik.postes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
